// <auto-generated />
using System;
using AngulerCRUDWithIdentity.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AngulerCRUDWithIdentity.Migrations
{
    [DbContext(typeof(paymentDbContext))]
    partial class paymentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AngulerCRUDWithIdentity.Model.PaymentInfo", b =>
                {
                    b.Property<int>("paymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal?>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("cardNumber")
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("cardOwnerName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("cvcNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("expiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("paymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("remarks")
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("paymentId");

                    b.ToTable("paymentInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
